<a href="https://colab.research.google.com/github/saadkamal219/Machine_Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

# xpoints = np.array([1, 10])
# ypoints = np.array([1, 20])

# print(arr.ndim)

# print(arr[0:1, ::-1])

# print(arr.dtype)

# newarr = arr.astype(bool)

# print(newarr)

# print(newarr.dtype)

# arr1 = arr.copy()

# arr[0,1] = 45

# print(arr)
# print(arr1)

# arr2 = arr.view()

# arr[0,1] = 55

# print(arr)
# print(arr2)

# print(arr.shape)

# arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8,9,10,11,12])
# arr2 = arr1.reshape(2,2,-1)
# print(arr2.ndim)
# newarr = arr.reshape(-1)
# print(arr.ndim)
# print(newarr.ndim)

# for i in arr:
#   for j in i:
#     print(j)

array = np.array([[1,2], [3,4]])
array2 = np.array([[5,6], [7,8]])

array3 = np.concatenate((array, array2), axis = 1)
print(array3)

print("\n")

array4 = np.stack((array, array2), axis = 0)
print(array4)

array = np.array_split(arr1,4)
print(array[0])
print(array[1])
print(array[2])
print(array[3])
# print(array[4])

print(np.sort(arr1))

new_arr = sorted(arr1, reverse=True)
print(new_arr)

[[1 2 5 6]
 [3 4 7 8]]


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
